apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-app
  namespace: test
  labels:
    app: load-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-test-app
  template:
    metadata:
      labels:
        app: load-test-app
    spec:
      containers:
      - name: load-test-app
        image: quang47/load-test-app
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: load-test-service
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: load-test-app
  ports:
    - port: 8080
      targetPort: 8080

 